### ISSUE TITLE
How to generate  XML-based file for mcpat?

### ISSUE THREAD

**Issue by LaneyLL** [werneazc/cgra-systemc#10]
Hello, mcpat need XML-based file as its input, but how can I get it from cgra-systemc repository？Thanks！

**Comment by werneazc** [comment]
Hello LaneyLL, that’s currently a bit hard. I am working to automize the procedure. In mcpat folder you will find some examples. For the corresponding PE you get an output file that contains its working and busy cycles. Those need to be put into the properties of the corresponding PEs in the XML file. The properties of interest are 

~~~
<stat name="total_instructions" value="3920881"/>
<stat name="int_instructions" value="0"/>
<stat name="store_instructions" value="3920881"/>
<stat name="total_cycles" value="3920881"/>
<stat name="idle_cycles" value="0"/>
<stat name="busy_cycles" value="3920881"/>
~~~

Int instructions are normal operations for PEs while store instructions are for the BUF operation.

Regards.
